List item tiles now display a prettier datetime format
amlcloud/screensite pull request #102
Opened 2023-01-30 08:01 UTC by chullman

Formatting is now "_YYYY-MM-DD at HH:mm:ss_" at 24 hour time.

![image](https://user-images.githubusercontent.com/36615723/215420140-3df1a976-2a8c-4004-b6ad-8aaede7b3bd5.png)

Instances of list items whose DateTime is empty (i.e. null) will have a default string of "_0001-01-01 at 00:00:00_" at 24 hour time.

![image](https://user-images.githubusercontent.com/36615723/215420420-37198a05-28dc-49b0-8dc5-72ef8c94e4ed.png)

2023-01-30 23:13 UTC, kovarny requested changes

2023-01-30 23:13 UTC, kovarny commented on lib/common.dart
> +  } else {
There is no value in this code other than to show an error. And we should not build any logic or write any code to account for some hypothetical app errors in the future.

2023-01-30 23:13 UTC, kovarny commented on lib/common.dart
> +String displayNeatTimestamp(DateTime? dateTime) {
Why making it null and account for null in it in such a way when we can make it just DateTime?

2023-01-30 23:13 UTC, kovarny commented on lib/common.dart
> +        Jiffy(dateTime).format(DISPLAY_TIME_FORMAT);
Why not have Jiffy(dateTime).format(DISPLAY_DATE_TIME_FORMAT)?

2023-01-31 00:41 UTC, chullman reviewed
I removed unneeded code to show an error on a hypothetical scenario. Now assumes DateTime will never be null

```dart
String displayNeatTimestamp(DateTime dateTime) {
  // Set DateTime argument to the format of yyyy-MM-dd HH:mm:ss (24-hour time)
  return Jiffy(dateTime).format(DISPLAY_DATE_TIME_FORMAT);
}
```

But in Debug now, entities that don't have the `lastUpdateTime` field will show the red error box:

![image](https://user-images.githubusercontent.com/36615723/215629130-de6f1177-bbc9-440d-85c4-500760c54d2a.png)

Is this ok?

2023-01-31 23:54 UTC, kovarny reviewed
spoke too much

2023-02-01 23:22 UTC, kovarny approved these changes

2023-02-01 23:23 UTC, kovarny approved these changes

2023-02-01 23:23 UTC, merged