added permission to use indexing features
amlcloud/screensite pull request #139
Opened 2023-02-21 02:11 UTC by wanlok

2023-02-21 23:47 UTC, kovarny requested changes

2023-02-21 23:47 UTC, kovarny commented on lib/lists/indexing/indexing_form.dart
> +                            doc.data()!['role'] == 'admin';
pls remove

2023-02-22 00:24 UTC, wanlok commented on lib/lists/indexing/indexing_form.dart
> +                            doc.data()!['role'] == 'admin';
Removed

2023-02-22 23:05 UTC, kovarny approved these changes

2023-02-23 12:31 UTC, merged