Refactored Search Page
amlcloud/screensite pull request #208
Opened 2023-07-19 08:03 UTC by taryarwinhtet

Separated everything into widget and method

2023-07-20 00:09 UTC, kovarny requested changes

2023-07-20 00:09 UTC, kovarny commented on lib/search/search_page.dart
> +  Container SearchButton(BuildContext context, void setSearchValue()) {
please follow the dart notation guidelines, and let's prefix build methods with 'build', e.g. buildSearchButton

2023-07-20 00:09 UTC, kovarny commented on lib/search/search_page.dart
> +class SearchPageInfo extends StatelessWidget {
pls move widgets to separate files.

2023-07-20 03:57 UTC, taryarwinhtet commented on lib/search/search_page.dart
> +class SearchPageInfo extends StatelessWidget {
resolved

2023-07-21 00:19 UTC, kovarny requested changes

2023-07-21 00:19 UTC, kovarny commented on lib/search/matches_ui.dart
> +class MatchesUI extends ConsumerWidget {
MatchesWidget

2023-07-21 00:19 UTC, kovarny commented on lib/search/profile_information_ui.dart
> +class ProfileInformationUI extends ConsumerWidget {
Please replace UI with Widget

2023-07-27 00:15 UTC, kovarny requested changes

2023-07-27 00:15 UTC, kovarny commented on lib/search/search_page.dart
> +                                buildSearchBar(setSearchValue),
I don't think this is the right way of doing it. Why do we need to pass a local function? Instead let's have it as a method that can be called in those methods.

2023-08-02 00:28 UTC, kovarny approved these changes

2023-09-06 00:18 UTC, closed without merging