Add timestamp to the search results details widget
amlcloud/screensite pull request #94
Opened 2023-01-26 00:14 UTC by karishmakarki1

This is the result. 

![Timestamp ](https://user-images.githubusercontent.com/122496030/214723207-586b53a3-c3dc-413d-8b93-8e7e1b05c0e6.png)

2023-01-26 23:04 UTC, kovarny requested changes

2023-01-26 23:04 UTC, kovarny commented on lib/search/search_details.dart
> +                  Text('Search Time:$time'),
Let's format the timestamp similar to lists page.

2023-01-26 23:04 UTC, kovarny commented on lib/search/search_details.dart
> +                  Text('Search Time:$time'),
Started: 10:01 am, 27 Jan, 2023

2023-01-29 10:00 UTC, wanlok requested changes
No need to import the jiffy library in main.dart. The datetime format is not the same as the screenhot in the kanban task card.

2023-01-30 07:19 UTC, karishmakarki1 commented
> No need to import the jiffy library in main.dart. The datetime format is not the same as the screenhot in the kanban task card.
Search_Details file:- Serge has requested to change the datetime format as 10:03 AM, 27 Jan, 2023. Please have a look in above. 
Main.dart file : I have removed the jiffy import. 
Please have a look .
 Thanks

2023-02-01 00:06 UTC, kovarny approved these changes

2023-02-01 00:06 UTC, kovarny approved these changes

2023-02-01 00:08 UTC, merged